### ISSUE TITLE
Docs have broken links to CIPs

### ISSUE THREAD

**Issue by m0ar** [ceramicstudio/js-composedb#171]
# Description
Most links from the docs to CIPs are broken as they link to a subdir, and the files seems to have moved up one step. Here are a couple of examples: https://composedb.js.org/docs/0.5.x/api/sdl/scalars#did

One of the broken links look like this: https://github.com/ceramicnetwork/CIPs/blob/main/CIPs/CIP-59/CIP-59.md#commitid where it should be https://github.com/ceramicnetwork/CIPs/blob/main/CIPs/cip-59.md#commitid (lowercase and dropped subdir)

**Comment by ashu26jha** [comment]
One more in the same page as above

Incorrect link (As in docs) : https://github.com/ceramicnetwork/CIPs/blob/main/CIPs/CIP-59/CIP-59.md#streamid
Correct link: https://github.com/ceramicnetwork/CIPs/blob/main/CIPs/cip-59.md#streamid

✌🏼

**Comment by oed** [comment]
Correct link should actually be:
https://cips.ceramic.network/CIPs/cip-59#commitid

**Comment by JustinaPetr** [comment]
Thank you for raising this @m0ar and @ashu26jha! Just pushed a fix for this.
