### ISSUE TITLE
Ensure DateTime scalar inputs are converted to string

### ISSUE THREAD

**Issue by PaulLeCam** [ceramicstudio/js-composedb#53]
# Description

The [`DateTime` scalar from the `graphql-scalars` library](https://www.the-guild.dev/graphql/scalars/docs/scalars/date-time) converts inputs to JS Date objects rather than strings as expected.
There is a [PR already open to fix the issue](https://github.com/Urigo/graphql-scalars/pull/1641) but we should address it directly here in the meantime.

# Technical Information

The [PR to fix the issue in `graphql-scalars`](https://github.com/Urigo/graphql-scalars/pull/1641) could a good solution to look into, implementing similar changes in our [`@composedb/graphql-scalars` package](https://github.com/ceramicstudio/js-composedb/tree/main/packages/graphql-scalars).

**Comment by morozj01** [comment]
@PaulLeCam 

It seems like [@composedb/graphql-scalars](https://github.com/ceramicstudio/js-composedb/blob/ca5c9b60e758d7865aec8d72f5fc94ecd7717168/packages/graphql-scalars/src/index.ts) is implemented as a simple pass through of the scalar types defined in the [graphql-scalars](https://www.npmjs.com/package/graphql-scalars) package.

The PR you referenced is fixing an issue in the `serialize` function of the datetime scalar which that package is exporting

I could implement a custom definition for the datetime [scalar type](https://graphql.org/graphql-js/type/#graphqlscalartype) (to use temporarily in place of the one being exported by [graphql-scalars](https://www.npmjs.com/package/graphql-scalars)) but that may be overkill for a package which is currently very simple - especially with a PR pending with a fix.

Happy to work on a temporary solution but wanted to get your feedback before proceeding.

**Comment by stbrody** [comment]
Shouldn't dates get converted into number types, or ideally to native date objects in the underlying db, so that range queries can work effectively?

**Comment by stbrody** [comment]
I guess the problem is that JSON doesn't have a native encoding for dates.  Sigh, this was one of the reasons that MongoDB's BSON added extra types beyond the base supported in JSON.  We might want to consider defining a JSON-compatible serialization format for dates so that Ceramic nodes can actually treat dates like dates

**Comment by morozj01** [comment]
Exactly - ceramic is importing a library which is supposed to serialize dates into strings already but there is a bug where it is not being done.

They have a PR open with a potential fix but it has been inactive for a while

https://github.com/ceramicstudio/js-composedb/pull/54
This could be a temporary solution if you think it's not worth waiting for them to merge that PR
@stbrody @PaulLeCam

**Comment by PaulLeCam** [comment]
Thanks @morozj01, I left some comments on your PR.

**Comment by ashutosh887** [comment]
@PaulLeCam I would like to continue working on it if needed

**Comment by PaulLeCam** [comment]
@ashutosh887 thanks but this has already been fixed in the mentioned PR, the latest version of ComposeDB packages have the fix.

**Comment by ashutosh887** [comment]
I'm willing to contribtute to the ecosystem @PaulLeCam 
Please let me know if there are any other issues I could pick

**Comment by PaulLeCam** [comment]
Thanks, there are some issues labelled as "good first issue" in the Ceramic repository: https://github.com/ceramicnetwork/js-ceramic/labels/good%20first%20issue

**Comment by ashutosh887** [comment]
Just saw... @PaulLeCam 
They look quite old... I'll check if they're already resolved
